export const alarmList = [
  {
    id: 1,
    type: "comment",
    content: "내 글에 댓글이 달렸어요",
    date: "2024-06-01 19:15",
    isRead: false,
    targetId: "1",
    targetType: "post",
    postTitle: "삼성 냉장고 팝니다",
  },
  {
    id: 2,
    type: "chat",
    content: "새로운 채팅이 있어요",
    date: "2024-06-01 18:55",
    isRead: false,
    targetId: "1",
    targetType: "chat",
    postTitle: "삼성 냉장고 팝니다",
  },
  {
    id: 3,
    type: "reply",
    content: "내 댓글에 답글이 달렸어요",
    date: "2024-06-01 16:23",
    isRead: true,
    targetId: "2",
    targetType: "post",
    postTitle: "중고 자전거 판매",
  },
  {
    id: 4,
    type: "chat",
    content: "새로운 채팅이 있어요",
    date: "2024-05-31 21:10",
    isRead: true,
    targetId: "2",
    targetType: "chat",
    postTitle: "중고 자전거 판매",
  },
];
